### ISSUE TITLE
[공지] github 활용 방법

### ISSUE THREAD

**Issue by nninzy** [nninzy/deepRun#2]
github 관련해서 어떻게 기록을 남기면 좋을지에 대해서 규칙이나 권장 사항등을 정리해봤습니다.

아직 깃허브를 활용한 경험이 적어서 이 방식이 최선의 방법이라고 장담할 수 없지만, 다들 깃과 깃허브에 대해서 연습해본다는 생각으로 많이 활용해주세요. 댓글로 더 좋은 방법에 대해서 건의해주시면 반영해서 내용 수정하도록 하겠습니다.

(읽었는지 확인차 미션이 있어요. 댓글 안달아주시면 다음 미팅때 왜 얘기 안해주시는지 추궁할 예정입니다)

## 01. github 기록 남기기

* 기록을 남기는 방법은 두가지가 있으며, 각각의 방법마다 진행하는 방식이 다릅니다. 원하는 방식으로 선택해서 진행해주세요. 
**(어떻게 진행할 계획인지 댓글로 남겨주세요.)**

    1. 스터디 **원본 repository에서 기록** 남기기

        * 노마드코더 닉네임으로 **branch 생성 후** 기록 진행 (README 관리용 branch는 manager, 저는 chloe 입니다)

        * git pull해서 업데이트 진행 필요

        * **main branch는 건들지 말아주세요. main에서 작업 시 PR을 남길 수 없습니다.**

        * 장점 = 본인 github 깔끔하게 유지 가능

        * 단점 = 매번 PR할때 스터디 원본 repository 찾아서 해야함

    2. 스터디 repository **fork 후 기록 남기기**

        * github 상단 오른쪽 fork 클릭 후 본인 github 내 fork된 repository에서 기록 진행

        * fork된 repository 내에서 Sync fork해서 업데이트 진행 필요

        * fork된 repository 내에서는 main branch로 이름이 시작되며 이때는 굳이 branch를 파실 필요 없습니다. 개인 공간이니까요.

        * 장점 = 본인 github에서 기록 관리 가능 / PR할때 원본 repository 찾을 필요 없음

        * 단점 = 본인 github에 기록이 남음(?)

* 기록은 **본인 폴더 내에서 자유롭게** 진행합니다. 타인을 위해서가 아니라 본인 스스로 기록하는 습관을 위해서 정리해주신다고 생각해주세요.

    * 본인 폴더 이름은 자유롭게 작성해주시면 되지만 노마드코더 닉네임을 권장합니다.
    (관심 받고 싶으시면 '귀욤뽀짝 XXX'같은 이름도 눈감아드려요 ^0^ 다만 다른 사람과 구분이 가게끔만!)

    * merge conflict 발생 위험을 줄이기 위해 다른 사람의 폴더는 침범하지 않으셨으면 좋겠습니다.
    (침범하고 conflict 발생 시 벌로 본인이 알아서 해결방법 찾아와서 wiki에 상.세.하.게. 해결 과정 기록 남겨주세요.)

* 폴더 내 README.md 파일을 생성해서 본인이 어떤 방식으로 기록을 남기고 있는지 설명해주시면 다른 사람들이 본인 폴더 내 내용을 볼 때 쉬울 것 같아 권장합니다.

## 02. github PR

* github PR은 본인이 한주간 기록한 내용을 올리는 곳입니다. 되도록이면 스터디 회의 전까지 올려주시면 좋지만 **주차별로 구분만 되게** 올려주세요.
(PR은 이전 PR이 merge가 진행되지 않는 이상 추가 생성할 수 없으며 push한 내용은 이전 PR에 들어가게 되니 주의해주세요.)
(merge 권한은 모두에게 드릴텐데 혹시나 안되면 언제든지 저를 불러주세요.)

* **PR하실때 반.드.시. Issues에 있는 해당 주차 계획 부분과 연결**해주세요!

  1. PR 제목 = [XX주차] (본인 닉네임) - (PR 주제)의 형식을 지켜서 올려주시길 권장합니다.
  (ex. [1주차] 클로이 - ch 4~7 독서 기록)

  2. PR 내용에 들어가면 좋을 것들 = 이번 PR에 대한 간략한 설명 (무엇을 기록했는지) / 이번 주차 책을 읽으면서 느낀점

## 03. github Issues

* 게시판의 기능으로, 주차별 계획, 공지사항 등이 올라갈 계획입니다. 그 외 자유롭게 이슈 말씀해주셔도 좋습니다. 주차별 계획 이슈에는 본인 PR을 연동해주세요.
(주차별 이슈는 [XX주차] (해당 주차 독서 범위) 와 같은 제목으로 올라옵니다.)

* 주차별 이슈 내 **댓글로 이번 주차와 관련해서 팀원들과 이야기하고 싶은 내용들, 주제들**(본인이 미팅 때 이 코드에 대해서 이야기할 것임. 각자 각오하셈 등)을 언급해주시면 정말 정말 좋습니다~

## 04. github Wiki

* 스터디 미팅 이후 나온 내용들이나 레퍼런스 등에 대한 기록이 진행될 예정입니다. 그 외에 본인이 팀원들과 공유하고 싶은 내용들, 문서들에 대해서 올려주시면 좋아요.
(미팅 이후 나온 내용들은 [XX주차] (미팅 진행 날짜, 스터디 회의 기록) 과 같은 제목으로 올라옵니다)

그럼 모두 화이팅!

**Comment by LikeRudin** [comment]
읽었습니다 화이팅

**Comment by nninzy** [comment]
> 읽었습니다 화이팅

슨생님 레포 관리 어떤 방식으로 하실건지 얘기 좀...

**Comment by naturalMin** [comment]
클로이님 아침부터 열심히 상세히 작성해주셨네요! 대박!! 쵝오!
저는 우선 2번 fork방식으로 기록진행하겠습니다.
저는 제 깃허브에도 공부기록이 남는게 좋은 것 같아서요 ㅎㅎ
이번주차도 홧팅!

**Comment by pollyjean** [comment]
이슈도 안보고 메인에 수정했네요. 반성 열번(뭘로?)하고 복구는 해놨습니다. 포크까지 해놨으면서...
저도 포크하고 폴더 만들어서 할게요.

**Comment by nninzy** [comment]
> 이슈도 안보고 메인에 수정했네요 반성 열번(뭘로?)하고 리버트 해놨습니다 포크하고 폴더 만들어서 정리하고 있습니다.
> 
> 저도 회사에서 하는거 받아만 써봐서,이렇게 하는 거는 또 다른 느낌(방법)이라... 여기저기 지저분하게 흔적이 남았네요. 그러면서 감은 잡은 거 같은데... 점점 나아지겠죠...

**Comment by primi-cream** [comment]
여러 일정 때문에 이제야 확인했네요.
매번 찾아야 하는 부분 때문에 저 또한 fork방식이 좋을 듯 합니다.
이러한 방식으로 정리하는 것은 처음이라 시간이 조금 걸리겠네요.
정리해주셔서 감사합니다.
